### ISSUE TITLE
Excel Export error - This site can't be reached

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/eypd#706]
**Describe the bug**
The Excel Export tool on earlyyearsbc.ca is not working. When I try to export a spreadsheet of users, I encounter an error screen (see screenshot below).

**To Reproduce**
1. Log in to the earlyyearsbc.ca WP dashboard.
2. Go to Tools > Excel Export.
3. Check the box that says "Include personally identifiable information in export".
4. Click the "Export Users" button (not the "Export" button above).
5. See error screen.

**Expected behavior**
When I click "Export Users", I expect an Excel spreadsheet to be generated and to automatically download. Instead, I encounter the error screen below.

**Screenshots**
Error screen:
![image](https://user-images.githubusercontent.com/44710357/75807246-dff33b00-5d39-11ea-8000-0c44f49a80e4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.122 (Official Build) (64-bit)

**Comment by dshaykewich** [comment]
The error reported in the email:

> When seeking help with this issue, you may be asked for some of the following information:
> WordPress version 5.3.2
> Current theme: Early Years Professional Development (version 1.2.0)
> Current plugin: Excel Export (version 1.0.0)
> PHP version 7.3.14
> 
> 
> 
> Error Details
> =============
> An error of type E_ERROR was caused in line 210 of the file /var/www/html/earlyyearsbc/wp-content/plugins/excel-export/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php. Error message: Uncaught Error: Class 'ZipArchive' not found in /var/www/html/earlyyearsbc/wp-content/plugins/excel-export/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php:210
> Stack trace:
> #0 /var/www/html/earlyyearsbc/wp-content/plugins/excel-export/inc/users/namespace.php(126): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save('/tmp/phpxltmpW0...')
> #1 /var/www/html/earlyyearsbc/wp-includes/class-wp-hook.php(288): BCcampus\Excel\Users\excel_export_users('')
> #2 /var/www/html/earlyyearsbc/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
> #3 /var/www/html/earlyyearsbc/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #4 /var/www/html/earlyyearsbc/wp-admin/admin.php(170): do_action('admin_init')
> #5 /var/www/html/earlyyearsbc/wp-admin/tools.php(22): require_once('/var/www/html/e...')
> #6 {main}
>   thrown

**Comment by kkilbey** [comment]
@alex-418 Just flagging this task as something to do before or during the week of March 16th in preparation for the EYPD transition. :)

**Comment by alex-418** [comment]
Thanks @kkilbey, this is a custom plugin we created for Kathreen to export some tables from the database. It's unclear if it's something that is still in use, or will be used in the future. @dshaykewich Will the new host require this functionality? Please let me know if I should spend time to fix and maintaining this custom plugin before the hand-off, or if it needs to be removed/retired instead.

**Comment by dshaykewich** [comment]
I have my meeting tomorrow.  I'll find out.

**Comment by paulagaube** [comment]
The custom export was useful to find duplicate locations and to see who was posting events, but also, I wonder about The Blob. If we keep this export functionality, @dshaykewich, will we need to include documentation on how to extract the info out of the blob?  (Just thinking out loud.)
